apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: exitcam
  namespace: dapr-bookcontrol
spec:
  type: bindings.mqtt
  version: v1
  metadata:
  - name: url
    value: mqtt://localhost:1883
  - name: topic
    value: bookcontrol/exitcam
  - name: consumerID
    value: "{uuid}"
scopes:
  - bookcontrolservice