apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secret-store
spec:
  type: secretstores.local.file
  metadata:
    - name: secretsFile
      value: /Users/eg/src/adesso/okr/2023Q4/DaprSecretManagement/DaprSecretManagement/components/secrets.json
