version: '3.4'
 
services:
  dapr-placement:
    image: daprio/dapr
    command: "./placement"
    ports:
      - "50005:50005"
    network_mode: "bridge"
 
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    network_mode: "bridge"
 
  myapp:
    image: adesso.dapr.crypt
    build: 
      context: ../src/Adesso.Dapr.Crypt
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DAPR_HTTP_PORT=3500
      - DAPR_GRPC_PORT=50001
    depends_on:
      - dapr-placement
      - redis
    command: [
      "dapr",
      "run",
      "--app-id", "myapp",
      "--app-port", "80",
      "--dapr-http-port", "3500",
      "--dapr-grpc-port", "50001",
      "--components-path", "/components",
      "--", "dotnet", "Adesso.Dapr.Crypt.dll"
    ]
    volumes:
      - "./components:/components"
    network_mode: "bridge"