apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: scheduleHttpJob
  namespace: default
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "@every 30s"