apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-secret-store
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: "<YOUR-VAULT-NAME>"
  - name: spnTenantId
    value: "<YOUR-TENANT-ID>"
  - name: spnClientId
    value: "<YOUR-CLIENT-ID>"
  - name: spnCertificate
    value: "<YOUR-CERTIFICATE>"